name: Release Single File

on:
  push:
    branches:
      - main

jobs:
  concatenate-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Concatenate files
        run: |
          echo -e "if SERVER then\r\n" > lua/autorun/sh_html_loader.lua
          cat lua/autorun/server/sv_html_loader.lua >> lua/autorun/sh_html_loader.lua
          echo -e "\r\n\r\nelse\r\n" >> lua/autorun/sh_html_loader.lua
          cat lua/autorun/client/cl_html_loader.lua >> lua/autorun/sh_html_loader.lua
          echo -e "\r\n\r\nend" >> lua/autorun/sh_html_loader.lua

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: concatenated-file
          path: lua/autorun/sh_html_loader.lua
