name: Release Single File

on:
  push:
    branches:
      - main

jobs:
  concatenate-and-create-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Concatenate files
        run: |
          echo -e "if SERVER then\r\n" > lua/autorun/sh_html_loader.lua
          cat lua/autorun/server/sv_html_loader.lua >> lua/autorun/sh_html_loader.lua
          echo -e "\r\n\r\nelse\r\n" >> lua/autorun/sh_html_loader.lua
          cat lua/autorun/client/cl_html_loader.lua >> lua/autorun/sh_html_loader.lua
          echo -e "\r\n\r\nend" >> lua/autorun/sh_html_loader.lua

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: concatenated-file
          path: lua/autorun/sh_html_loader.lua

  publish-artifact:
    needs: concatenate-and-create-artifact
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: concatenated-file

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: Single file release from source files
          draft: false
          prerelease: false

      - name: Create release asset
        id: create_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.create_release.upload_url }}
          asset_path: ./lua/autorun/sh_html_loader.lua
          asset_name: sh_html_loader.lua
          asset_content_type: text/plain

      - name: Display download URL
        run: echo "Download at ${{ steps.create_asset.outputs.browser_download_url }}"
